name: bulkRNA
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - r-essentials
  - r-base
  - star
  - htseq
  - pip
  - r-curl
  - samtools
  - jupyterlab
  - bioconductor-deseq2
  - r-pheatmap
  - r-ggplot2

